export type RedundancyLane = {
  id: string;
  name: string;
  rationale: string;
  keywords: string[];
  primaryCite: string;
  seeCite: string;
};

export const REDUNDANCY_LANES: RedundancyLane[] = [
  {
    id: "lane-01",
    name: "Limited Use definition restated",
    rationale: "Canonical definition lives in 10–12; B–10 and 7–3 should cite, not redefine.",
    keywords: ["limited use", "protected evidence", "self-referral"],
    primaryCite: "10-12",
    seeCite: "See para 10–12 (Limited Use Policy definition).",
  },
  {
    id: "lane-02",
    name: "Confidentiality restated",
    rationale: "42 CFR Part 2 rules should not be rewritten in EAP, ethics, and legal chapters independently.",
    keywords: ["confidentiality", "42 cfr", "patient records", "hipaa"],
    primaryCite: "10-15",
    seeCite: "See paras 10–14 through 10–30.",
  },
  {
    id: "lane-03",
    name: "Commander referral duty",
    rationale: "Early referral language repeats in 1–7, 2–30, 7–1, and B–2.",
    keywords: ["refer", "command referred", "early identification", "intervene early"],
    primaryCite: "7-1",
    seeCite: "See para 7–1 and appendix B.",
  },
  {
    id: "lane-04",
    name: "Self-identification path",
    rationale: "Self-ID appears in 7–3, B–5, and Limited Use discussion.",
    keywords: ["self-identification", "voluntary", "self-referral", "seeks help"],
    primaryCite: "7-3",
    seeCite: "See para 7–3.",
  },
  {
    id: "lane-05",
    name: "ADAPT referral timeline",
    rationale: "Completion window is restated across responsibilities, alcohol, and training chapters.",
    keywords: ["adapt", "prevention training", "complete the course"],
    primaryCite: "9-14",
    seeCite: "See para 9–14.",
  },
  {
    id: "lane-06",
    name: "UDL certification",
    rationale: "Qualifications appear in 2–33, 9–6, and B–11.",
    keywords: ["unit deterrence leader", "udl", "certified"],
    primaryCite: "9-6",
    seeCite: "See para 9–6.",
  },
  {
    id: "lane-07",
    name: "Smart testing restated",
    rationale: "Technique list in 4–10 should not be duplicated in B–12.",
    keywords: ["smart testing", "unpredictable", "cannot predict"],
    primaryCite: "4-10",
    seeCite: "See para 4–10.",
  },
  {
    id: "lane-08",
    name: "Collection SOP versus chapter 4",
    rationale: "4–11 through 4–13 overlap appendix D.",
    keywords: ["collection procedures", "specimen bottle", "observer", "dd form 2624"],
    primaryCite: "D-5",
    seeCite: "See appendix D.",
  },
  {
    id: "lane-09",
    name: "MRO review",
    rationale: "MRO process repeats in 4–14, 15–8, and 16–7.",
    keywords: ["medical review officer", "mro", "legitimate medical"],
    primaryCite: "4-14",
    seeCite: "See para 4–14.",
  },
  {
    id: "lane-10",
    name: "Use of positive results",
    rationale: "Table 10–1 / para 10–3 should be the single use-of-results rule.",
    keywords: ["confirmed positive", "use of", "test result"],
    primaryCite: "10-3",
    seeCite: "See para 10–3.",
  },
  {
    id: "lane-11",
    name: "Separation actions",
    rationale: "Do not copy AR 635-200 / 135-178 process into 10–6, 15–10, or 16–16.",
    keywords: ["separation", "administrative separation", "characterization"],
    primaryCite: "10-6",
    seeCite: "See para 10–6 and the governing separation regulation.",
  },
  {
    id: "lane-12",
    name: "Civilian TDP rules",
    rationale: "TDP identification and suspension appear in multiple chapter 5 paragraphs.",
    keywords: ["testing designated position", "tdp", "drug-free workplace"],
    primaryCite: "5-8",
    seeCite: "See para 5–8.",
  },
  {
    id: "lane-13",
    name: "DOT overlap",
    rationale: "DOT alcohol (chap 3) and DOT drug (chap 5) should cross-cite shared SAP rules.",
    keywords: ["department of transportation", "dot", "safety-sensitive"],
    primaryCite: "5-22",
    seeCite: "See paras 5–22 through 5–34.",
  },
  {
    id: "lane-14",
    name: "ARNG versus USAR testing",
    rationale: "Chapters 15 and 16 restate common testing and MRO rules.",
    keywords: ["army national guard", "u.s. army reserve", "state adjutant", "usar"],
    primaryCite: "4-6",
    seeCite: "See para 4–6 for common RC testing policy.",
  },
  {
    id: "lane-15",
    name: "Aftercare versus treatment",
    rationale: "Aftercare (8–5) should not repeat full treatment criteria (8–2).",
    keywords: ["aftercare", "rehabilitation team", "mandatory treatment"],
    primaryCite: "8-5",
    seeCite: "See para 8–5.",
  },
  {
    id: "lane-16",
    name: "Records and DAMIS",
    rationale: "Reporting language repeats in 1–5, chapter 14, 16–14.",
    keywords: ["damis", "records management", "arims"],
    primaryCite: "14-1",
    seeCite: "See chapter 14.",
  },
  {
    id: "lane-17",
    name: "Prevention training hours",
    rationale: "Soldier, civilian, Family, and leadership training paragraphs overlap.",
    keywords: ["awareness training", "prevention, education", "gambling disorder"],
    primaryCite: "9-2",
    seeCite: "See para 9–2.",
  },
  {
    id: "lane-18",
    name: "Eligibility restated",
    rationale: "Eligibility in 1–8 is restated in chapters 6, 15, and 16.",
    keywords: ["eligibility", "eligible to receive", "family members"],
    primaryCite: "1-8",
    seeCite: "See para 1–8.",
  },
  {
    id: "lane-19",
    name: "Program authority",
    rationale: "Statutory basis should live in 1–6, not in every component chapter.",
    keywords: ["public law", "dodi 1010", "program authority"],
    primaryCite: "1-6",
    seeCite: "See para 1–6.",
  },
  {
    id: "lane-20",
    name: "Risk reduction factors",
    rationale: "Table 12–1 definitions should not be rewritten in IPT or URI paragraphs.",
    keywords: ["high-risk", "unit risk inventory", "risk reduction"],
    primaryCite: "12-1",
    seeCite: "See chapter 12.",
  },
  {
    id: "lane-21",
    name: "Awards versus campaigns",
    rationale: "Award criteria and community campaign language overlap in chapter 17.",
    keywords: ["award", "campaign", "community drug awareness"],
    primaryCite: "17-2",
    seeCite: "See para 17–2.",
  },
  {
    id: "lane-22",
    name: "Ethics versus confidentiality",
    rationale: "Appendix F confidentiality should cite chapter 10 rather than restate penalties.",
    keywords: ["professional code", "client protections", "unauthorized disclosure"],
    primaryCite: "F-3",
    seeCite: "See appendix F and paras 10–14 through 10–30.",
  },
];
